### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by claytontey** [marcoscleison/PyOPF#2]
Hello, good afternoon ... I will try to install PyOPF, and I have the following errors:
The attached image shows the result for the setup, if then, I execute the teste.py file, I get the following error:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pyopf import OPFClassifier
  File "/home/clayton/PyOPF/pyopf/__init__.py", line 16, in <module>
    from .pyopf import OPFClassifier, OPFClustering
  File "/home/clayton/PyOPF/pyopf/pyopf.py", line 16, in <module>
    import pyopf_native as opfn
ImportError: /home/clayton/PyOPF/pyopf_native.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __kmpc_critical

![Screenshot from 2019-06-25 17-51-49](https://user-images.githubusercontent.com/5413320/60132538-140d6980-9772-11e9-9853-22bbfc58bac3.png)

I Would like to thanks for your help.... hugs

**Comment by marcoscleison** [comment]
Hi, We suspect that this is related to openmp. Trey to install the openmv dev libraries and try to compile again.
We are working to create a heel, to make things easier. Of course, we would like to share the library in pip index, but it is in alpha yet.
